version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  backend:
    build:
      context: .
      dockerfile: src/PyFiles/Dockerfile
    ports:
      - "8080:8080"
