# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Install dependencies for Chrome and ChromeDriver
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    unzip \
    libx11-dev \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libgl1-mesa-glx \
    libgtk-3-0 \
    libnss3 \
    libasound2 \
    libxtst6 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libappindicator3-1 \
    libgdk-pixbuf2.0-0 \
    libgbm1 \
    xdg-utils \
    fonts-liberation \
    libvulkan1 \
    gnupg \
    gcc \
    libpq-dev \
    libnss3 \
    libgconf-2-4 \
    libxss1 \
    && rm -rf /var/lib/apt/lists/*

# Last ned og installer Google Chrome
RUN curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o google-chrome-stable_current_amd64.deb \
    && dpkg -i google-chrome-stable_current_amd64.deb || apt-get -f install -y \
    && rm google-chrome-stable_current_amd64.deb

# Legg Google Chrome til PATH
ENV PATH=$PATH:/usr/bin

# Debug Google Chrome
RUN which google-chrome-stable && google-chrome-stable --version

# Installer Python-avhengigheter
WORKDIR /app
COPY src/PyFiles/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Debug Chromedriver-autoinstaller
RUN python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"

# Copy the requirements file from the current directory (src/PyFiles) into the container's /app directory
COPY src/PyFiles/requirements.txt .

# Install the dependencies inside the container
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port that Flask will run on
EXPOSE 8000

# Run the Flask app
CMD ["python", "app.py"]
