# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build, deploy Docker app + WebJob to Azure

env:
  AZURE_WEBAPP_NAME: 'theemailfinder'
  DOCKER_IMAGE_NAME: 'krisdocker307/theemailfinder'
  DOCKER_IMAGE_TAG: 'latest'
  DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}
  DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
  DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/theemailfinder:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/theemailfinder:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Prepare WebJob ZIP
        run: |
          echo "Creating WebJob directory structure..."
          rm -rf webjobemailsearch
          mkdir -p webjobemailsearch/src/PyFiles
          
          echo "Copying WebJob files..."
          # Copy root level files
          cp App_Data/jobs/triggered/webjobemailsearch/run_email_search.py webjobemailsearch/
          cp App_Data/jobs/triggered/webjobemailsearch/requirements.txt webjobemailsearch/
          cp App_Data/jobs/triggered/webjobemailsearch/test.py webjobemailsearch/
          cp App_Data/jobs/triggered/webjobemailsearch/settings.job webjobemailsearch/
          cp App_Data/jobs/triggered/webjobemailsearch/run.cmd webjobemailsearch/
          
          # Copy PyFiles with verbose output
          echo "Copying PyFiles directory contents..."
          cp -v App_Data/jobs/triggered/webjobemailsearch/src/PyFiles/*.py webjobemailsearch/src/PyFiles/
          
          echo "Setting file permissions..."
          chmod -R 755 webjobemailsearch
          
          echo "Verifying directory structure..."
          ls -la webjobemailsearch/
          ls -la webjobemailsearch/src/PyFiles/
          
          echo "Creating ZIP file..."
          cd webjobemailsearch && zip -r ../webjobemailsearch.zip . && cd ..
          
          echo "WebJob ZIP contents:"
          unzip -l webjobemailsearch.zip

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          environment: azurecloud
          allow-no-subscriptions: true

      - name: Deploy to Azure Web App (Docker)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.DOCKER_USERNAME }}/theemailfinder:latest

      - name: Set environment variables in Azure Web App
        run: |
          az webapp config appsettings set \
            --resource-group theemailfinder \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --settings DATABASE_CONNECTION_STRING=${{ secrets.DATABASE_CONNECTION_STRING }}

      - name: Upload WebJob ZIP via Kudu API
        run: |
          echo "Uploading WebJob ZIP to Kudu..."
          curl -X PUT -u "$DEPLOY_USER:$DEPLOY_PASS" \
              --data-binary @"webjobemailsearch.zip" \
              -H "Content-Type: application/zip" \
              -v \
              https://theemailfinder-d8ctecfsaab2a7fh.scm.norwayeast-01.azurewebsites.net/api/zip/site/wwwroot/App_Data/jobs/triggered/webjobemailsearch/

      - name: Wait for Azure to process changes
        run: |
          echo "Waiting for Azure to process changes..."
          sleep 90
          echo "Proceeding with deployment..."

