# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Dockerized Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: 'theemailfinder'
  DOCKER_IMAGE_NAME: 'krisdocker307/theemailfinder'
  DOCKER_IMAGE_TAG: 'latest'
  DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/theemailfinder:latest -f src/PyFiles/Dockerfile src/PyFiles
          docker push ${{ secrets.DOCKER_USERNAME }}/theemailfinder:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DDBDA77844C646369677A222E2103256 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BB5321127104439390C66CECBF7EC4CD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BB4BC7F4E9BC423BBB5BD24ABD63DF97 }}
          auth-type: 'AzureCli'  # Set auth-type to SERVICE_PRINCIPAL
          environment: azurecloud
          allow-no-subscriptions: true
          

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
